kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Values.appname }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Values.appname }}(/|$)(.*)
            backend:
              serviceName: {{ .Values.appname }}-srv
              servicePort: {{ .Values.containerPort }}